/* =========================================================================
   COTA-CERO — Traduccions
   L'idioma base és el castellà: és el que hi ha escrit a l'HTML.

   LA CLAU ÉS LA FRASE EN CASTELLÀ, tal com surt a la pàgina. Si canvieu una
   frase de l'HTML i no la canvieu aquí, es quedarà en l'idioma base: lleig,
   però no enganya ningú.

   CRITERI (l'escriu qui tradueix, abans de la primera frase; és el que
   llegeixen els lots següents per no contradir-se):
   · TRACTAMENT: la web parla de tú («Pide presupuesto», «tu reforma»). En
     català, tu («Demana pressupost», «la teva reforma»); en anglès, directe
     («Get a quote»). Empresa de reformes seriosa i propera: frases curtes,
     concretes, sense to publicitari.
   · CTA fix: «Pedir presupuesto» → «Demanar pressupost» / «Get a quote».
   · OFICI: «presupuesto cerrado» → «pressupost tancat» / «fixed-price quote»;
     «reforma integral» → «reforma integral» / «full renovation»; «escombro»
     → «runa» / «rubble»; «alicatado» → «enrajolat» / «tiling»; «bajantes» →
     «baixants» / «drainpipes»; «plato de ducha» → «plat de dutxa» / «shower
     tray»; «jefe de obra» → «cap d'obra» / «site manager»; «entrega de
     llaves» → «lliurament de claus» / «handover».
   · PLÀNOL: les cotes (480, 320…) són centímetres sense separador i van a
     `igual`. Noms d'estança: Cocina/Cuina/Kitchen, Baño/Bany/Bathroom,
     Salón/Menjador/Living room, Dormitorio/Dormitori/Bedroom.
   · TESTIMONIS: són text provisional d'aquesta demo, no cites reals: SÍ que
     es tradueixen (per això no porten data-idioma-original).
   · NO ES TRADUEIXEN (van a `igual`): Cota Cero, Cota Cero Reformas,
     600 000 000, noms de persona (Marta G., Jordi P., Ana R.…), ±0.
   · Els terminis són orientatius: mantenir «orientativo» → «orientatiu» /
     «approximate».
   · MARCADORS DELS LEGALS: es queden igual a les tres versions (§8.I).

   El bloc entre TRAD:inici i TRAD:fi el reescriu
   `node recursos-comuns/i18n-prepara.mjs aplica`: els comentaris que s'hi
   posin es perden. El criteri va aquí dalt.
   ========================================================================= */

/* ── TRAD:inici ── generat per i18n-prepara.mjs aplica ── */
window.TRAD = {
  "igual": [
    "Cota Cero",
    "© 2026 Cota Cero Reformas",
    "Ana R.",
    "Jordi P.",
    "Marta G.",
    "Email",
    "Google Fonts",
    "www.aepd.es"
  ],
  "ca": {
    "Datos identificativos, objeto, propiedad intelectual y condiciones de uso de esta web.": "Dades identificatives, objecte, propietat intel·lectual i condicions d'ús d'aquesta web.",
    "Saltar al contenido": "Saltar al contingut",
    "Cota Cero Reformas, inicio": "Cota Cero Reformas, inici",
    "Principal": "Principal",
    "Reformas integrales": "Reformes integrals",
    "Cocinas": "Cuines",
    "Baños": "Banys",
    "Llamar al 600 000 000": "Trucar al 600 000 000",
    "Idioma de la página": "Idioma de la pàgina",
    "Pedir presupuesto": "Demanar pressupost",
    "Menú": "Menú",
    "Inicio": "Inici",
    "/ Aviso legal": "/ Avís legal",
    "Aviso legal": "Avís legal",
    "1. Datos identificativos del titular": "1. Dades identificatives del titular",
    "En cumplimiento del deber de información recogido en el artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), se informa de los siguientes datos:": "En compliment del deure d'informació recollit a l'article 10 de la Llei 34/2002, d'11 de juliol, de serveis de la societat de la informació i de comerç electrònic (LSSI-CE), s'informa de les dades següents:",
    "Nombre comercial: Cota Cero Reformas.": "Nom comercial: Cota Cero Reformas.",
    "Razón social: [RAZÓN SOCIAL].": "Raó social: [RAZÓN SOCIAL].",
    "NIF: [NIF].": "NIF: [NIF].",
    "Domicilio: [DOMICILIO].": "Domicili: [DOMICILIO].",
    "Correo electrónico de contacto: [EMAIL DE CONTACTO].": "Correu electrònic de contacte: [EMAIL DE CONTACTO].",
    "Teléfono: 600 000 000.": "Telèfon: 600 000 000.",
    "Inscripción registral: [REGISTRO MERCANTIL].": "Inscripció registral: [REGISTRO MERCANTIL].",
    "2. Objeto": "2. Objecte",
    "Esta web tiene como finalidad informar sobre los servicios de reformas de Cota Cero Reformas y permitir a quien la visita solicitar un presupuesto. El acceso y uso de este sitio atribuye la condición de usuario y supone la aceptación de las condiciones recogidas en este aviso legal.": "Aquesta web té com a finalitat informar sobre els serveis de reformes de Cota Cero Reformas i permetre a qui la visita sol·licitar un pressupost. L'accés i l'ús d'aquest lloc atribueix la condició d'usuari i suposa l'acceptació de les condicions recollides en aquest avís legal.",
    "3. Propiedad intelectual e industrial": "3. Propietat intel·lectual i industrial",
    "Los textos, imágenes, diseño gráfico, código y demás contenidos de esta web son titularidad de Cota Cero Reformas o de terceros que han autorizado su uso, y están protegidos por la normativa de propiedad intelectual e industrial. No se permite su reproducción, distribución o transformación sin autorización previa por escrito del titular.": "Els textos, imatges, disseny gràfic, codi i altres continguts d'aquesta web són propietat de Cota Cero Reformas o de tercers que n'han autoritzat l'ús, i estan protegits per la normativa de propietat intel·lectual i industrial. No es permet la seva reproducció, distribució o transformació sense autorització prèvia per escrit del titular.",
    "4. Responsabilidad": "4. Responsabilitat",
    "Cota Cero Reformas no garantiza la ausencia de errores en el acceso a la web ni que su contenido esté siempre actualizado, aunque pondrá los medios razonables para evitarlos y corregirlos. Tampoco se responsabiliza de los daños que pudieran derivarse de interferencias, omisiones, interrupciones, virus informáticos o desconexiones en el funcionamiento operativo del sistema electrónico.": "Cota Cero Reformas no garanteix l'absència d'errors en l'accés a la web ni que el seu contingut estigui sempre actualitzat, tot i que posarà els mitjans raonables per evitar-los i corregir-los. Tampoc es responsabilitza dels danys que puguin derivar-se d'interferències, omissions, interrupcions, virus informàtics o desconnexions en el funcionament operatiu del sistema electrònic.",
    "5. Ley aplicable y fuero": "5. Llei aplicable i fur",
    "Las presentes condiciones se rigen por la legislación española. Para la resolución de cualquier controversia derivada del acceso o uso de esta web, las partes se someten a los juzgados y tribunales que correspondan según la normativa vigente en materia de consumidores y usuarios.": "Aquestes condicions es regeixen per la legislació espanyola. Per resoldre qualsevol controvèrsia derivada de l'accés o l'ús d'aquesta web, les parts se sotmeten als jutjats i tribunals que corresponguin segons la normativa vigent en matèria de consumidors i usuaris.",
    "Reformamos desde el plano hasta la entrega de llaves.": "Reformem des del plànol fins al lliurament de claus.",
    "Reformas": "Reformes",
    "Contacto": "Contacte",
    "Privacidad": "Privacitat",
    "Cookies": "Galetes",
    "Escribir por WhatsApp": "Escriure per WhatsApp",
    "Aviso legal · Cota Cero Reformas": "Avís legal · Cota Cero Reformas",
    "Reforma integral de baños: fontanería, alicatado, sanitarios y mampara, con presupuesto cerrado y fecha de entrega.": "Reforma integral de banys: fontaneria, enrajolat, sanitaris i mampara, amb pressupost tancat i data de lliurament.",
    "· Baños": "· Banys",
    "Un baño nuevo, revisado desde las bajantes": "Un bany nou, revisat des dels baixants",
    "Cambiamos lo que se ve y lo que no: instalaciones, alicatado y sanitarios.": "Canviem el que es veu i el que no: instal·lacions, enrajolat i sanitaris.",
    "Llamar": "Trucar",
    "Foto: baño terminado, ducha a ras de suelo y mampara, 16:9": "Foto: bany acabat, dutxa arran de terra i mampara, 16:9",
    "Qué incluye": "Què inclou",
    "Fontanería y desagües renovados": "Fontaneria i desguassos renovats",
    "Sanitarios: inodoro, lavabo, ducha o bañera": "Sanitaris: inodor, lavabo, dutxa o banyera",
    "Mampara o cortina, a elegir": "Mampara o cortina, a triar",
    "Alicatado y suelo": "Enrajolat i terra",
    "Impermeabilización antes de alicatar": "Impermeabilització abans d'enrajolar",
    "Ventilación: extractor o renovación del conducto": "Ventilació: extractor o renovació del conducte",
    "Iluminación y enchufes con toma de tierra revisada": "Il·luminació i endolls amb la presa de terra revisada",
    "Cómo lo hacemos": "Com ho fem",
    "Bajantes e impermeabilización": "Baixants i impermeabilització",
    "Revisamos primero las bajantes y la impermeabilización, no solo lo que se ve al final.": "Primer revisem els baixants i la impermeabilització, no només el que es veu al final.",
    "El baño entero": "El bany sencer",
    "Levantamos el baño entero: alicatado, sanitarios y suelo, no parche sobre parche.": "Aixequem el bany sencer: enrajolat, sanitaris i terra, no pedaç sobre pedaç.",
    "Oficios coordinados": "Oficis coordinats",
    "Coordinamos fontanero y alicatador para no tener el baño parado entre oficios.": "Coordinem el fontaner i l'enrajolador perquè el bany no quedi aturat entre oficis.",
    "Prueba de agua": "Prova d'aigua",
    "Probamos el agua y los desagües antes de dar la obra por terminada.": "Provem l'aigua i els desguassos abans de donar l'obra per acabada.",
    "Foto: baño antes, bañera y alicatado antiguo, 4:3": "Foto: bany abans, banyera i enrajolat antic, 4:3",
    "Foto: baño terminado, ducha a ras de suelo, 4:3": "Foto: bany acabat, dutxa arran de terra, 4:3",
    "Antes": "Abans",
    "Después": "Després",
    "Comparar antes y después del baño sin bañera": "Comparar l'abans i el després del bany sense banyera",
    "Baño": "Bany",
    "Baño sin bañera": "Bany sense banyera",
    "Cambiamos una bañera que ya no se usaba por un plato de ducha a ras de suelo y revisamos toda la fontanería.": "Vam canviar una banyera que ja no s'utilitzava per un plat de dutxa arran de terra i vam revisar tota la fontaneria.",
    "Al levantar el plato de ducha encontraron una fuga que no se veía. Nos avisaron antes de arreglarla y no nos cobraron de más por ello. El baño quedó listo una semana después de lo previsto, pero sabíamos por qué.": "En aixecar el plat de dutxa van trobar una fuita que no es veia. Ens van avisar abans d'arreglar-la i no ens van cobrar de més per això. El bany va quedar llest una setmana després del previst, però sabíem per què.",
    "Preguntas frecuentes": "Preguntes freqüents",
    "¿El presupuesto incluye la demolición?": "El pressupost inclou la demolició?",
    "Sí. Retirar el baño antiguo y sacar el escombro está incluido en el precio cerrado, no aparece después como extra.": "Sí. Retirar el bany antic i treure la runa està inclòs en el preu tancat, no apareix després com a extra.",
    "¿Cuánto dura la obra de un baño?": "Quant dura l'obra d'un bany?",
    "Entre 2 y 4 semanas, según si tocamos solo acabados o también la instalación. Es un plazo orientativo, lo cerramos en el presupuesto.": "Entre 2 i 4 setmanes, segons si toquem només els acabats o també la instal·lació. És un termini orientatiu, el tanquem en el pressupost.",
    "¿Hace falta permiso para reformar el baño?": "Cal permís per reformar el bany?",
    "Si solo cambias acabados y sanitarios, normalmente no. Si mueves la distribución o las bajantes, lo comprobamos y gestionamos lo necesario.": "Si només canvies els acabats i els sanitaris, normalment no. Si mous la distribució o els baixants, ho comprovem i gestionem el que calgui.",
    "¿Y si aparece una fuga o una humedad al empezar?": "I si apareix una fuita o una humitat en començar?",
    "Te lo enseñamos antes de tocar nada y te decimos qué cuesta arreglarlo. No se hace nada que no hayas aprobado.": "T'ho ensenyem abans de tocar res i et diem què costa arreglar-ho. No fem res que no hagis aprovat.",
    "¿Qué garantía tiene la impermeabilización?": "Quina garantia té la impermeabilització?",
    "La misma que el resto de la obra: por escrito, en el contrato.": "La mateixa que la resta de l'obra: per escrit, al contracte.",
    "También hacemos": "També fem",
    "Muebles, electrodomésticos e instalaciones nuevas, coordinados para no alargar la obra.": "Mobles, electrodomèstics i instal·lacions noves, coordinats per no allargar l'obra.",
    "Distribución, instalaciones y acabados coordinados de principio a fin.": "Distribució, instal·lacions i acabats coordinats de principi a fi.",
    "¿Reformamos tu baño?": "Reformem el teu bany?",
    "Presupuesto cerrado, con la fontanería revisada desde el primer día.": "Pressupost tancat, amb la fontaneria revisada des del primer dia.",
    "O llámanos:": "O truca'ns:",
    "Baños · Cota Cero Reformas": "Banys · Cota Cero Reformas",
    "Reforma integral de cocinas: muebles, electrodomésticos, instalaciones y acabados, con presupuesto cerrado y fecha de entrega.": "Reforma integral de cuines: mobles, electrodomèstics, instal·lacions i acabats, amb pressupost tancat i data de lliurament.",
    "/ Cocinas": "/ Cuines",
    "Una cocina nueva, con fecha de entrega firmada": "Una cuina nova, amb data de lliurament signada",
    "Foto: cocina terminada, encimera y frente, 16:9": "Foto: cuina acabada, encimera i frontal, 16:9",
    "Muebles de cocina a medida, según el espacio": "Mobles de cuina a mida, segons l'espai",
    "Encimera y frente, a elegir el material": "Encimera i frontal, a triar el material",
    "Electrodomésticos nuevos, o instalación de los tuyos": "Electrodomèstics nous, o instal·lació dels teus",
    "Instalación eléctrica y de fontanería renovadas": "Instal·lació elèctrica i de fontaneria renovades",
    "Extracción de humos y ventilación": "Extracció de fums i ventilació",
    "Suelo y alicatado": "Terra i enrajolat",
    "Iluminación y enchufes donde los necesites, no donde quedaban antes": "Il·luminació i endolls on els necessitis, no on quedaven abans",
    "Medimos primero": "Primer mesurem",
    "Medimos y dibujamos la cocina contigo antes de pedir ni un mueble.": "Mesurem i dibuixem la cuina amb tu abans de demanar ni un moble.",
    "Margen en los pedidos": "Marge en les comandes",
    "Pedimos los materiales con margen, para no parar la obra esperando un envío.": "Demanem els materials amb marge, per no aturar l'obra esperant un enviament.",
    "Coordinamos electricista, fontanero y montador para que no se pisen entre ellos.": "Coordinem l'electricista, el fontaner i el muntador perquè no es trepitgin entre ells.",
    "Resto de la casa protegido": "Resta de la casa protegida",
    "Protegemos el resto de la casa mientras dura la obra de la cocina.": "Protegim la resta de la casa mentre dura l'obra de la cuina.",
    "Foto: cocina antes de la reforma, tabique cerrado, 4:3": "Foto: cuina abans de la reforma, envà tancat, 4:3",
    "Foto: cocina terminada, isla y luz natural, 4:3": "Foto: cuina acabada, illa i llum natural, 4:3",
    "Comparar antes y después de la cocina en forma de L": "Comparar l'abans i el després de la cuina en forma de L",
    "Cocina": "Cuina",
    "Cocina en forma de L": "Cuina en forma de L",
    "Sustituimos una cocina cerrada y con poca luz por una cocina abierta al comedor, con isla y ventilación nueva.": "Vam substituir una cuina tancada i amb poca llum per una cuina oberta al menjador, amb illa i ventilació nova.",
    "Pedimos que la cocina no nos quitara más de un mes porque cocinábamos con placa eléctrica en el salón. La acabaron en 24 días, justo dentro de lo que nos habían dicho. La isla quedó donde la dibujamos el primer día.": "Vam demanar que la cuina no ens tragués més d'un mes perquè cuinàvem amb una placa elèctrica al menjador. La van acabar en 24 dies, just dins del que ens havien dit. L'illa va quedar on la vam dibuixar el primer dia.",
    "¿El precio puede subir a mitad de obra?": "El preu pot pujar a mitja obra?",
    "No. El presupuesto que firmas incluye todas las partidas. Si surge algo imprevisto, te lo decimos antes de hacerlo, no en la factura final.": "No. El pressupost que signes inclou totes les partides. Si sorgeix algun imprevist, t'ho diem abans de fer-ho, no a la factura final.",
    "¿Cuánto tarda una cocina?": "Quant triga una cuina?",
    "Entre 3 y 5 semanas, según el tamaño y si hay que mover instalaciones. Es un plazo orientativo: te damos la fecha exacta en el presupuesto.": "Entre 3 i 5 setmanes, segons la mida i si cal moure instal·lacions. És un termini orientatiu: et donem la data exacta al pressupost.",
    "¿Necesito algún permiso?": "Necessito algun permís?",
    "Depende de si cambias la distribución o solo los acabados. Lo comprobamos en la visita y, si hace falta, nos encargamos del trámite.": "Depèn de si canvies la distribució o només els acabats. Ho comprovem a la visita i, si cal, ens encarreguem del tràmit.",
    "¿Puedo seguir cocinando en casa durante la obra?": "Puc seguir cuinant a casa durant l'obra?",
    "Durante los días de instalación eléctrica y de fontanería, no. El resto de la obra no impide usar el resto de la casa.": "Durant els dies d'instal·lació elèctrica i de fontaneria, no. La resta de l'obra no impedeix fer servir la resta de la casa.",
    "¿Qué pasa si algo falla después de terminar?": "Què passa si alguna cosa falla després d'acabar?",
    "Queda cubierto por la garantía por escrito del contrato. Nos llamas y volvemos.": "Queda cobert per la garantia per escrit del contracte. Ens truques i tornem.",
    "¿Empezamos por tu cocina?": "Comencem per la teva cuina?",
    "Pide presupuesto y te lo entregamos por escrito, partida por partida.": "Demana pressupost i te'l lliurem per escrit, partida per partida.",
    "Cocinas · Cota Cero Reformas": "Cuines · Cota Cero Reformas",
    "Cuéntanos tu reforma y te enviamos un presupuesto cerrado, sin compromiso.": "Explica'ns la teva reforma i t'enviem un pressupost tancat, sense compromís.",
    "/ Contacto": "/ Contacte",
    "Pide tu presupuesto": "Demana el teu pressupost",
    "Cuéntanos qué quieres reformar y te contactamos con un presupuesto cerrado.": "Explica'ns què vols reformar i et contactem amb un pressupost tancat.",
    "Tipo de obra": "Tipus d'obra",
    "Reforma integral": "Reforma integral",
    "Otra": "Altra",
    "m² aproximados": "m² aproximats",
    "(opcional)": "(opcional)",
    "Nombre": "Nom",
    "Teléfono": "Telèfon",
    "Mensaje": "Missatge",
    "He leído y acepto la": "He llegit i accepto la",
    "política de privacidad": "política de privacitat",
    "Qué pasa después": "Què passa després",
    "Revisamos tu solicitud y, si falta algún dato, te llamamos para completarlo.": "Revisem la teva sol·licitud i, si falta alguna dada, et truquem per completar-la.",
    "Concretamos una visita para ver la vivienda, sin compromiso.": "Concretem una visita per veure l'habitatge, sense compromís.",
    "Te entregamos el presupuesto cerrado, por escrito, en los días siguientes a la visita.": "Et lliurem el pressupost tancat, per escrit, els dies següents a la visita.",
    "¿Prefieres hablarlo?": "Prefereixes parlar-ho?",
    "Contacto · Cota Cero Reformas": "Contacte · Cota Cero Reformas",
    "Reformamos cocinas, baños y viviendas completas con presupuesto cerrado y fecha de entrega en contrato. Pide presupuesto sin compromiso.": "Reformem cuines, banys i habitatges complets amb pressupost tancat i data de lliurament al contracte. Demana pressupost sense compromís.",
    "Antes de tocar una pared, hacemos el plano": "Abans de tocar una paret, fem el plànol",
    "Precio cerrado, fecha firmada y un equipo que no cambia a mitad de obra.": "Preu tancat, data signada i un equip que no canvia a mitja obra.",
    "Esquina de un plano de vivienda con sus medidas": "Cantonada d'un plànol d'habitatge amb les seves mides",
    "Así se dibuja tu reforma": "Així es dibuixa la teva reforma",
    "Elige la estancia y te contamos qué hacemos, cómo y en cuánto tiempo.": "Tria l'estança i t'expliquem què fem, com i en quant de temps.",
    "Plano de una vivienda: cocina, baño y el resto de la casa": "Plànol d'un habitatge: cuina, bany i la resta de la casa",
    "Toda la casa": "Tota la casa",
    "Salón": "Menjador",
    "Dormitorio": "Dormitori",
    "Cambiamos la cocina completa: muebles, electrodomésticos, instalación eléctrica y de agua, y acabados. Coordinamos los oficios para no tenerla parada más de lo necesario.": "Canviem la cuina completa: mobles, electrodomèstics, instal·lació elèctrica i d'aigua, i acabats. Coordinem els oficis per no tenir-la aturada més del necessari.",
    "Plazo orientativo: entre 3 y 5 semanas.": "Termini orientatiu: entre 3 i 5 setmanes.",
    "Ver cocinas": "Veure cuines",
    "Renovamos el baño desde cero: fontanería, alicatado, sanitarios y mampara. Revisamos primero las bajantes y la impermeabilización, no solo lo que se ve.": "Renovem el bany des de zero: fontaneria, enrajolat, sanitaris i mampara. Revisem primer els baixants i la impermeabilització, no només el que es veu.",
    "Plazo orientativo: entre 2 y 4 semanas.": "Termini orientatiu: entre 2 i 4 setmanes.",
    "Ver baños": "Veure banys",
    "Nos encargamos de la vivienda completa: distribución, instalaciones, carpintería y acabados, con un solo interlocutor.": "Ens encarreguem de l'habitatge complet: distribució, instal·lacions, fusteria i acabats, amb un sol interlocutor.",
    "Plazo orientativo: entre 8 y 14 semanas, según los metros.": "Termini orientatiu: entre 8 i 14 setmanes, segons els metres.",
    "Ver reformas integrales": "Veure reformes integrals",
    "Lo que firmamos contigo": "El que signem amb tu",
    "Las tres cosas que más preocupan antes de una reforma son el precio, el plazo y el desorden. Por eso van en el contrato.": "Les tres coses que més preocupen abans d'una reforma són el preu, el termini i el desordre. Per això van al contracte.",
    "Precio cerrado por escrito": "Preu tancat per escrit",
    "Lo que firmamos es lo que pagas, sin partidas que aparecen a mitad de obra.": "El que signem és el que pagues, sense partides que apareixen a mitja obra.",
    "Fecha en el contrato": "Data al contracte",
    "La entrega tiene una fecha firmada, no una estimación de boca.": "El lliurament té una data signada, no una estimació de paraula.",
    "Equipo propio": "Equip propi",
    "Los oficios que entran en tu casa son nuestro equipo, no subcontratas de última hora.": "Els oficis que entren a casa teva són el nostre equip, no subcontractes de darrera hora.",
    "Obra limpia cada día": "Obra neta cada dia",
    "Antes de irnos, recogemos: escombro fuera y suelos protegidos, todos los días.": "Abans de marxar, recollim: runa fora i terres protegits, cada dia.",
    "Garantía por escrito": "Garantia per escrit",
    "Lo que hacemos queda garantizado por contrato, no de palabra.": "El que fem queda garantit per contracte, no de paraula.",
    "De la visita a las llaves": "De la visita a les claus",
    "Visita": "Visita",
    "Vemos la vivienda y hablamos de lo que necesitas, sin compromiso.": "Veiem l'habitatge i parlem del que necessites, sense compromís.",
    "Presupuesto cerrado": "Pressupost tancat",
    "Te lo entregamos por escrito, partida por partida.": "Te'l lliurem per escrit, partida per partida.",
    "Planificación": "Planificació",
    "Fijamos fechas, materiales y quién hace qué, antes de tocar nada.": "Fixem dates, materials i qui fa què, abans de tocar res.",
    "Obra": "Obra",
    "Empezamos en la fecha acordada y protegemos lo que no se reforma.": "Comencem en la data acordada i protegim el que no es reforma.",
    "Entrega de llaves": "Lliurament de claus",
    "Revisamos juntos cada detalle antes de darte la vivienda por terminada.": "Revisem junts cada detall abans de donar l'habitatge per acabat.",
    "Antes y después": "Abans i després",
    "Arrastra la línea para comparar.": "Arrossega la línia per comparar.",
    "Foto: piso antes de la reforma, distribución original, 4:3": "Foto: pis abans de la reforma, distribució original, 4:3",
    "Foto: piso terminado, salón abierto, 4:3": "Foto: pis acabat, menjador obert, 4:3",
    "Comparar antes y después del piso de los años 70": "Comparar l'abans i el després del pis dels anys 70",
    "Piso de los años 70": "Pis dels anys 70",
    "Redistribuimos un piso con pasillos estrechos y habitaciones cerradas: ahora tiene un salón más grande y un baño más.": "Vam redistribuir un pis amb passadissos estrets i habitacions tancades: ara té un menjador més gran i un bany més.",
    "Lo que cuentan después": "El que expliquen després",
    "Nos dieron el presupuesto cerrado antes de empezar y no cambió ni un euro en toda la obra. Recogían el escombro cada tarde, así que seguíamos viviendo cerca sin que fuera un caos. La entrega fue el día que decía el contrato.": "Ens van donar el pressupost tancat abans de començar i no va canviar ni un euro en tota l'obra. Recollien la runa cada tarda, així que seguíem vivint a prop sense que fos un caos. El lliurament va ser el dia que deia el contracte.",
    "Pide tu presupuesto, sin compromiso": "Demana el teu pressupost, sense compromís",
    "Te lo entregamos por escrito, con precio cerrado y fecha de entrega.": "Te'l lliurem per escrit, amb preu tancat i data de lliurament.",
    "Cota Cero Reformas · Reformas integrales, cocinas y baños": "Cota Cero Reformas · Reformes integrals, cuines i banys",
    "Esta web no usa cookies propias ni de analítica. Qué recursos externos carga y qué información pueden recibir.": "Aquesta web no fa servir cookies pròpies ni d'analítica. Quins recursos externs carrega i quina informació poden rebre.",
    "/ Cookies": "/ Galetes",
    "Política de cookies": "Política de cookies",
    "1. Esta web no usa cookies propias": "1. Aquesta web no fa servir cookies pròpies",
    "Cota Cero Reformas no instala cookies propias ni de analítica en tu navegador. No hay medición de tráfico, ni perfiles de navegación, ni publicidad basada en tu actividad en esta web.": "Cota Cero Reformas no instal·la cookies pròpies ni d'analítica al teu navegador. No hi ha mesurament de trànsit, ni perfils de navegació, ni publicitat basada en la teva activitat en aquesta web.",
    "2. Sin recursos de terceros al navegar": "2. Sense recursos de tercers mentre navegues",
    "Las tipografías y la librería que anima el plano están alojadas en esta misma web. Mientras navegas, tu navegador no hace peticiones a servidores de otras empresas.": "Les tipografies i la llibreria que anima el plànol estan allotjades en aquesta mateixa web. Mentre navegues, el teu navegador no fa peticions a servidors d'altres empreses.",
    "3. Formulario de contacto": "3. Formulari de contacte",
    "Si rellenas y envías el formulario de la página «Pedir presupuesto», los datos que escribes se envían a Formspree, Inc., el proveedor que gestiona la recepción de esos formularios. Este envío ocurre solo si tú decides enviar el formulario; se detalla en la": "Si omples i envies el formulari de la pàgina «Demanar pressupost», les dades que escrius s'envien a Formspree, Inc., el proveïdor que gestiona la recepció d'aquests formularis. Aquest enviament es produeix només si tu decideixes enviar el formulari; es detalla a la",
    "4. Cambios en esta política": "4. Canvis en aquesta política",
    "Si en algún momento añadimos analítica o cualquier servicio que use cookies, lo indicaremos aquí y te pediremos permiso antes de activarlo.": "Si en algun moment afegim analítica o qualsevol servei que faci servir galetes, ho indicarem aquí i et demanarem permís abans d'activar-lo.",
    "Política de cookies · Cota Cero Reformas": "Política de cookies · Cota Cero Reformas",
    "Qué datos recogemos al pedir presupuesto, con qué finalidad y cómo ejercer tus derechos de protección de datos.": "Quines dades recollim en demanar pressupost, amb quina finalitat i com exercir els teus drets de protecció de dades.",
    "/ Privacidad": "/ Privacitat",
    "Política de privacidad": "Política de privacitat",
    "1. Responsable del tratamiento": "1. Responsable del tractament",
    "2. Datos que recogemos y finalidad": "2. Dades que recollim i finalitat",
    "A través del formulario de la página «Pedir presupuesto» recogemos los siguientes datos: tipo de obra, metros cuadrados aproximados (opcional), nombre, teléfono, correo electrónico (opcional) y el mensaje que quieras añadir. Los usamos únicamente para responder a tu solicitud de presupuesto: contactarte, concretar una visita y, en su caso, entregarte el presupuesto por escrito.": "A través del formulari de la pàgina «Demanar pressupost» recollim les dades següents: tipus d'obra, metres quadrats aproximats (opcional), nom, telèfon, correu electrònic (opcional) i el missatge que vulguis afegir. Les fem servir únicament per respondre la teva sol·licitud de pressupost: contactar-te, concretar una visita i, si escau, lliurar-te el pressupost per escrit.",
    "3. Base legal": "3. Base legal",
    "El tratamiento se basa en tu consentimiento, que prestas al marcar la casilla de privacidad y enviar el formulario, y en la aplicación de medidas precontractuales a petición tuya (artículo 6.1.b del RGPD), ya que nos escribes para pedir un presupuesto.": "El tractament es basa en el teu consentiment, que dones en marcar la casella de privacitat i enviar el formulari, i en l'aplicació de mesures precontractuals a petició teva (article 6.1.b del RGPD), ja que ens escrius per demanar un pressupost.",
    "4. Encargado del tratamiento": "4. Encarregat del tractament",
    "El formulario de contacto se gestiona a través de Formspree, Inc., con sede en Estados Unidos, que actúa como encargado del tratamiento y recibe los datos que envías para hacérnoslos llegar. Formspree aplica sus propias garantías de seguridad; puedes consultar su política de privacidad en su web.": "El formulari de contacte es gestiona a través de Formspree, Inc., amb seu als Estats Units, que actua com a encarregat del tractament i rep les dades que envies per fer-nos-les arribar. Formspree aplica les seves pròpies garanties de seguretat; pots consultar la seva política de privacitat al seu lloc web.",
    "5. Conservación de los datos": "5. Conservació de les dades",
    "Conservamos los datos mientras dure la relación con la solicitud de presupuesto y, tras finalizar, durante los plazos legales aplicables para atender posibles responsabilidades. Pasado ese tiempo, se eliminan o se anonimizan.": "Conservem les dades mentre duri la relació amb la sol·licitud de pressupost i, un cop finalitzada, durant els terminis legals aplicables per atendre possibles responsabilitats. Passat aquest temps, s'eliminen o s'anonimitzen.",
    "6. Tus derechos": "6. Els teus drets",
    "Puedes ejercer tus derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad escribiendo a [EMAIL DE CONTACTO], indicando el derecho que quieres ejercer y adjuntando un documento que acredite tu identidad.": "Pots exercir els teus drets d'accés, rectificació, supressió, oposició, limitació del tractament i portabilitat escrivint a [EMAIL DE CONTACTO], indicant el dret que vols exercir i adjuntant un document que acrediti la teva identitat.",
    "7. Reclamación ante la autoridad de control": "7. Reclamació davant l'autoritat de control",
    "Si consideras que el tratamiento de tus datos no se ajusta a la normativa, puedes presentar una reclamación ante la Agencia Española de Protección de Datos (AEPD),": "Si consideres que el tractament de les teves dades no s'ajusta a la normativa, pots presentar una reclamació davant l'Agencia Española de Protección de Datos (AEPD),",
    "Política de privacidad · Cota Cero Reformas": "Política de privacitat · Cota Cero Reformas",
    "Reforma integral de la vivienda: distribución, instalaciones, carpintería y acabados, con un solo interlocutor y presupuesto cerrado.": "Reforma integral de l'habitatge: distribució, instal·lacions, fusteria i acabats, amb un sol interlocutor i pressupost tancat.",
    "/ Reformas integrales": "/ Reformes integrals",
    "Toda la casa, con un solo interlocutor": "Tota la casa, amb un sol interlocutor",
    "Foto: salón reformado, luz natural, 16:9": "Foto: menjador reformat, llum natural, 16:9",
    "Redistribución de espacios, si hace falta": "Redistribució d'espais, si cal",
    "Instalación eléctrica y de fontanería completas": "Instal·lació elèctrica i de fontaneria completes",
    "Carpintería interior y exterior": "Fusteria interior i exterior",
    "Suelos y alicatados de toda la vivienda": "Terres i enrajolats de tot l'habitatge",
    "Pintura y acabados": "Pintura i acabats",
    "Cocina y baños incluidos en el proyecto": "Cuina i banys inclosos en el projecte",
    "Gestión de permisos y trámites con la comunidad": "Gestió de permisos i tràmits amb la comunitat",
    "Empezamos por el plano": "Comencem pel plànol",
    "Empezamos por el plano: cómo quieres distribuir la vivienda y por qué.": "Comencem pel plànol: com vols distribuir l'habitatge i per què.",
    "Planificamos el orden": "Planifiquem l'ordre",
    "Planificamos el orden de los oficios antes de pedir el primer material.": "Planifiquem l'ordre dels oficis abans de demanar el primer material.",
    "Un jefe de obra": "Un cap d'obra",
    "Un jefe de obra es tu único contacto durante toda la reforma.": "Un cap d'obra és el teu únic contacte durant tota la reforma.",
    "Revisamos el avance": "Revisem l'avanç",
    "Revisamos el avance cada semana contigo, no solo al final.": "Revisem l'avanç cada setmana amb tu, no només al final.",
    "¿El precio cerrado incluye cocina y baños?": "El preu tancat inclou cuina i banys?",
    "Si están dentro del proyecto que presupuestamos, sí. Todo lo acordado va en el mismo precio, sin partidas sueltas después.": "Si estan dins del projecte que pressupostem, sí. Tot el que s'acorda va en el mateix preu, sense partides soltes després.",
    "¿Cuánto dura una reforma integral?": "Quant dura una reforma integral?",
    "Entre 8 y 14 semanas, según los metros y si cambia la distribución. Es un plazo orientativo: te damos la fecha real en el presupuesto.": "Entre 8 i 14 setmanes, segons els metres i si canvia la distribució. És un termini orientatiu: et donem la data real al pressupost.",
    "¿Quién se encarga de los permisos?": "Qui s'encarrega dels permisos?",
    "Nosotros. Comprobamos qué necesita tu comunidad o el ayuntamiento y hacemos el trámite antes de empezar.": "Nosaltres. Comprovem què necessita la teva comunitat o l'ajuntament i fem el tràmit abans de començar.",
    "¿Dónde va el escombro?": "On va la runa?",
    "Lo retiramos con contenedor autorizado y lo recogemos cada día de obra, no se acumula en la vivienda.": "La retirem amb contenidor autoritzat i la recollim cada dia d'obra, no s'acumula a l'habitatge.",
    "¿Qué garantía tiene la reforma completa?": "Quina garantia té la reforma completa?",
    "La misma en toda la obra: por escrito, en el contrato, sin depender de a quién le preguntes.": "La mateixa a tota l'obra: per escrit, al contracte, sense dependre de a qui preguntis.",
    "¿Empezamos por el plano de tu casa?": "Comencem pel plànol de casa teva?",
    "Visita, presupuesto cerrado y fecha de entrega firmada.": "Visita, pressupost tancat i data de lliurament signada.",
    "Reformas integrales · Cota Cero Reformas": "Reformes integrals · Cota Cero Reformas",
    "después": "després",
    "Escribe tu nombre.": "Escriu el teu nom.",
    "Escribe un teléfono de al menos 9 cifras.": "Escriu un telèfon d'almenys 9 xifres.",
    "Necesitamos que aceptes la política de privacidad.": "Cal que acceptis la política de privacitat.",
    "Enviando…": "Enviant…",
    "Recibido. Te llamamos en un día laborable para concretar la visita.": "Rebut. Et truquem en un dia laborable per concretar la visita.",
    "No se ha podido enviar. Llámanos al 600 000 000 y lo vemos por teléfono.": "No s'ha pogut enviar. Truca'ns al 600 000 000 i ho mirem per telèfon.",
    "2. Recursos externos que se cargan": "2. Recursos externs que es carreguen",
    "Aun sin usar cookies, la página carga algunos recursos alojados en servidores de terceros para funcionar correctamente. Al cargarlos, esos terceros pueden recibir tu dirección IP y datos técnicos propios de cualquier petición a un servidor web:": "Tot i no fer servir cookies, la pàgina carrega alguns recursos allotjats en servidors de tercers per funcionar correctament. En carregar-los, aquests tercers poden rebre la teva adreça IP i dades tècniques pròpies de qualsevol petició a un servidor web:",
    ": las tipografías del sitio (Bricolage Grotesque y Source Serif 4) se cargan desde los servidores de Google Fonts.": ": les tipografies del lloc (Bricolage Grotesque i Source Serif 4) es carreguen des dels servidors de Google Fonts.",
    "GSAP (vía cdnjs, Cloudflare)": "GSAP (via cdnjs, Cloudflare)",
    ": la librería que anima el dibujo del plano en la portada se carga desde la red de Cloudflare (cdnjs).": ": la llibreria que anima el dibuix del plànol a la portada es carrega des de la xarxa de Cloudflare (cdnjs).",
    "4. Cómo desactivar estos recursos": "4. Com desactivar aquests recursos",
    "Puedes bloquear estas peticiones a terceros desde la configuración de tu navegador o con una extensión de bloqueo; la web seguirá funcionando, aunque puede que el texto o la animación del plano se vean con el estilo por defecto del navegador.": "Pots bloquejar aquestes peticions a tercers des de la configuració del teu navegador o amb una extensió de bloqueig; la web continuarà funcionant, tot i que és possible que el text o l'animació del plànol es vegin amb l'estil per defecte del navegador."
  },
  "en": {
    "Datos identificativos, objeto, propiedad intelectual y condiciones de uso de esta web.": "Identification details, purpose, intellectual property and terms of use of this website.",
    "Saltar al contenido": "Skip to content",
    "Cota Cero Reformas, inicio": "Cota Cero Reformas, home",
    "Principal": "Main",
    "Reformas integrales": "Full renovations",
    "Cocinas": "Kitchens",
    "Baños": "Bathrooms",
    "Llamar al 600 000 000": "Call 600 000 000",
    "Idioma de la página": "Page language",
    "Pedir presupuesto": "Get a quote",
    "Menú": "Menu",
    "Inicio": "Home",
    "/ Aviso legal": "/ Legal notice",
    "Aviso legal": "Legal notice",
    "1. Datos identificativos del titular": "1. Identification details of the owner",
    "En cumplimiento del deber de información recogido en el artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), se informa de los siguientes datos:": "In compliance with the duty of information set out in Article 10 of Law 34/2002, of 11 July, on Information Society Services and Electronic Commerce (LSSI-CE), the following details are provided:",
    "Nombre comercial: Cota Cero Reformas.": "Trade name: Cota Cero Reformas.",
    "Razón social: [RAZÓN SOCIAL].": "Registered company name: [RAZÓN SOCIAL].",
    "NIF: [NIF].": "NIF: [NIF].",
    "Domicilio: [DOMICILIO].": "Address: [DOMICILIO].",
    "Correo electrónico de contacto: [EMAIL DE CONTACTO].": "Contact email: [EMAIL DE CONTACTO].",
    "Teléfono: 600 000 000.": "Telephone: 600 000 000.",
    "Inscripción registral: [REGISTRO MERCANTIL].": "Registration details: [REGISTRO MERCANTIL].",
    "2. Objeto": "2. Purpose",
    "Esta web tiene como finalidad informar sobre los servicios de reformas de Cota Cero Reformas y permitir a quien la visita solicitar un presupuesto. El acceso y uso de este sitio atribuye la condición de usuario y supone la aceptación de las condiciones recogidas en este aviso legal.": "This website aims to provide information about Cota Cero Reformas' renovation services and to let visitors request a quote. Accessing and using this site makes you a user and implies acceptance of the terms set out in this legal notice.",
    "3. Propiedad intelectual e industrial": "3. Intellectual and industrial property",
    "Los textos, imágenes, diseño gráfico, código y demás contenidos de esta web son titularidad de Cota Cero Reformas o de terceros que han autorizado su uso, y están protegidos por la normativa de propiedad intelectual e industrial. No se permite su reproducción, distribución o transformación sin autorización previa por escrito del titular.": "The texts, images, graphic design, code and other content on this website belong to Cota Cero Reformas or to third parties who have authorised their use, and are protected by intellectual and industrial property law. Reproduction, distribution or alteration is not allowed without prior written authorisation from the owner.",
    "4. Responsabilidad": "4. Liability",
    "Cota Cero Reformas no garantiza la ausencia de errores en el acceso a la web ni que su contenido esté siempre actualizado, aunque pondrá los medios razonables para evitarlos y corregirlos. Tampoco se responsabiliza de los daños que pudieran derivarse de interferencias, omisiones, interrupciones, virus informáticos o desconexiones en el funcionamiento operativo del sistema electrónico.": "Cota Cero Reformas does not guarantee that the website will be error-free or that its content is always up to date, although it will take reasonable steps to prevent and correct any issues. Nor is it liable for any damage arising from interference, omissions, interruptions, computer viruses or disconnections in the operation of the electronic system.",
    "5. Ley aplicable y fuero": "5. Governing law and jurisdiction",
    "Las presentes condiciones se rigen por la legislación española. Para la resolución de cualquier controversia derivada del acceso o uso de esta web, las partes se someten a los juzgados y tribunales que correspondan según la normativa vigente en materia de consumidores y usuarios.": "These terms are governed by Spanish law. Any dispute arising from access to or use of this website will be submitted to the courts that apply under current consumer protection legislation.",
    "Reformamos desde el plano hasta la entrega de llaves.": "We handle everything from the floor plan to handover.",
    "Reformas": "Renovations",
    "Contacto": "Contact",
    "Privacidad": "Privacy",
    "Cookies": "Cookies",
    "Escribir por WhatsApp": "Message us on WhatsApp",
    "Aviso legal · Cota Cero Reformas": "Legal notice · Cota Cero Reformas",
    "Reforma integral de baños: fontanería, alicatado, sanitarios y mampara, con presupuesto cerrado y fecha de entrega.": "Full bathroom renovation: plumbing, tiling, sanitaryware and shower screen, with a fixed-price quote and delivery date.",
    "· Baños": "· Bathrooms",
    "Un baño nuevo, revisado desde las bajantes": "A new bathroom, checked from the drainpipes up",
    "Cambiamos lo que se ve y lo que no: instalaciones, alicatado y sanitarios.": "We change what you see and what you don't: installations, tiling and sanitaryware.",
    "Llamar": "Call",
    "Foto: baño terminado, ducha a ras de suelo y mampara, 16:9": "Photo: finished bathroom, walk-in shower and screen, 16:9",
    "Qué incluye": "What's included",
    "Fontanería y desagües renovados": "Renovated plumbing and drains",
    "Sanitarios: inodoro, lavabo, ducha o bañera": "Sanitaryware: toilet, basin, shower or bath",
    "Mampara o cortina, a elegir": "Screen or curtain, your choice",
    "Alicatado y suelo": "Tiling and flooring",
    "Impermeabilización antes de alicatar": "Waterproofing before tiling",
    "Ventilación: extractor o renovación del conducto": "Ventilation: extractor fan or duct renewal",
    "Iluminación y enchufes con toma de tierra revisada": "Lighting and sockets with the earth connection checked",
    "Cómo lo hacemos": "How we work",
    "Bajantes e impermeabilización": "Drainpipes and waterproofing",
    "Revisamos primero las bajantes y la impermeabilización, no solo lo que se ve al final.": "We check the drainpipes and waterproofing first, not just what shows at the end.",
    "El baño entero": "The whole bathroom",
    "Levantamos el baño entero: alicatado, sanitarios y suelo, no parche sobre parche.": "We strip the whole bathroom: tiling, sanitaryware and flooring, not patch on patch.",
    "Oficios coordinados": "Trades, coordinated",
    "Coordinamos fontanero y alicatador para no tener el baño parado entre oficios.": "We coordinate the plumber and the tiler so the bathroom isn't left idle between trades.",
    "Prueba de agua": "Water test",
    "Probamos el agua y los desagües antes de dar la obra por terminada.": "We test the water and the drains before we call the job finished.",
    "Foto: baño antes, bañera y alicatado antiguo, 4:3": "Photo: bathroom before, bath and old tiling, 4:3",
    "Foto: baño terminado, ducha a ras de suelo, 4:3": "Photo: finished bathroom, walk-in shower, 4:3",
    "Antes": "Before",
    "Después": "After",
    "Comparar antes y después del baño sin bañera": "Compare before and after of the bathroom without a bath",
    "Baño": "Bathroom",
    "Baño sin bañera": "Bathroom without a bath",
    "Cambiamos una bañera que ya no se usaba por un plato de ducha a ras de suelo y revisamos toda la fontanería.": "We replaced a bath that wasn't being used with a walk-in shower tray and checked all the plumbing.",
    "Al levantar el plato de ducha encontraron una fuga que no se veía. Nos avisaron antes de arreglarla y no nos cobraron de más por ello. El baño quedó listo una semana después de lo previsto, pero sabíamos por qué.": "When they lifted the shower tray they found a leak we couldn't see. They told us before fixing it and didn't charge us extra for it. The bathroom was ready a week later than planned, but we knew why.",
    "Preguntas frecuentes": "Frequently asked questions",
    "¿El presupuesto incluye la demolición?": "Does the quote include demolition?",
    "Sí. Retirar el baño antiguo y sacar el escombro está incluido en el precio cerrado, no aparece después como extra.": "Yes. Removing the old bathroom and clearing the rubble is included in the fixed price, it won't show up later as an extra.",
    "¿Cuánto dura la obra de un baño?": "How long does a bathroom renovation take?",
    "Entre 2 y 4 semanas, según si tocamos solo acabados o también la instalación. Es un plazo orientativo, lo cerramos en el presupuesto.": "Between 2 and 4 weeks, depending on whether we only touch the finishes or the installation too. It's an approximate timeframe, we confirm it in the quote.",
    "¿Hace falta permiso para reformar el baño?": "Do I need a permit to renovate a bathroom?",
    "Si solo cambias acabados y sanitarios, normalmente no. Si mueves la distribución o las bajantes, lo comprobamos y gestionamos lo necesario.": "If you're only changing the finishes and sanitaryware, usually not. If you move the layout or the drainpipes, we'll check and sort out whatever's needed.",
    "¿Y si aparece una fuga o una humedad al empezar?": "What if a leak or damp shows up once we start?",
    "Te lo enseñamos antes de tocar nada y te decimos qué cuesta arreglarlo. No se hace nada que no hayas aprobado.": "We show you before touching anything and tell you what it costs to fix. We don't do anything you haven't approved.",
    "¿Qué garantía tiene la impermeabilización?": "What warranty does the waterproofing have?",
    "La misma que el resto de la obra: por escrito, en el contrato.": "The same as the rest of the work: in writing, in the contract.",
    "También hacemos": "We also do",
    "Muebles, electrodomésticos e instalaciones nuevas, coordinados para no alargar la obra.": "New units, appliances and installations, coordinated so the job doesn't drag on.",
    "Distribución, instalaciones y acabados coordinados de principio a fin.": "Layout, installations and finishes coordinated from start to finish.",
    "¿Reformamos tu baño?": "Shall we renovate your bathroom?",
    "Presupuesto cerrado, con la fontanería revisada desde el primer día.": "Fixed-price quote, with the plumbing checked from day one.",
    "O llámanos:": "Or call us:",
    "Baños · Cota Cero Reformas": "Bathrooms · Cota Cero Reformas",
    "Reforma integral de cocinas: muebles, electrodomésticos, instalaciones y acabados, con presupuesto cerrado y fecha de entrega.": "Full kitchen renovation: units, appliances, installations and finishes, with a fixed-price quote and delivery date.",
    "/ Cocinas": "/ Kitchens",
    "Una cocina nueva, con fecha de entrega firmada": "A new kitchen, with a signed delivery date",
    "Foto: cocina terminada, encimera y frente, 16:9": "Photo: finished kitchen, worktop and splashback, 16:9",
    "Muebles de cocina a medida, según el espacio": "Made-to-measure kitchen units, sized to the space",
    "Encimera y frente, a elegir el material": "Worktop and splashback, choose the material",
    "Electrodomésticos nuevos, o instalación de los tuyos": "New appliances, or we fit your own",
    "Instalación eléctrica y de fontanería renovadas": "Renovated electrics and plumbing",
    "Extracción de humos y ventilación": "Smoke extraction and ventilation",
    "Suelo y alicatado": "Flooring and tiling",
    "Iluminación y enchufes donde los necesites, no donde quedaban antes": "Lighting and sockets where you need them, not where they used to be",
    "Medimos primero": "We measure first",
    "Medimos y dibujamos la cocina contigo antes de pedir ni un mueble.": "We measure and design the kitchen with you before ordering a single unit.",
    "Margen en los pedidos": "Margin on orders",
    "Pedimos los materiales con margen, para no parar la obra esperando un envío.": "We order materials with margin, so the job doesn't stall waiting for a delivery.",
    "Coordinamos electricista, fontanero y montador para que no se pisen entre ellos.": "We coordinate the electrician, plumber and fitter so they don't get in each other's way.",
    "Resto de la casa protegido": "Rest of the house protected",
    "Protegemos el resto de la casa mientras dura la obra de la cocina.": "We protect the rest of the house for as long as the kitchen work lasts.",
    "Foto: cocina antes de la reforma, tabique cerrado, 4:3": "Photo: kitchen before the renovation, closed-off wall, 4:3",
    "Foto: cocina terminada, isla y luz natural, 4:3": "Photo: finished kitchen, island and natural light, 4:3",
    "Comparar antes y después de la cocina en forma de L": "Compare before and after of the L-shaped kitchen",
    "Cocina": "Kitchen",
    "Cocina en forma de L": "L-shaped kitchen",
    "Sustituimos una cocina cerrada y con poca luz por una cocina abierta al comedor, con isla y ventilación nueva.": "We replaced a closed-off, dim kitchen with one open to the dining room, with an island and new ventilation.",
    "Pedimos que la cocina no nos quitara más de un mes porque cocinábamos con placa eléctrica en el salón. La acabaron en 24 días, justo dentro de lo que nos habían dicho. La isla quedó donde la dibujamos el primer día.": "We asked for the kitchen not to take more than a month because we were cooking on an electric hob in the living room. They finished it in 24 days, right within what they'd told us. The island ended up exactly where we'd sketched it on day one.",
    "¿El precio puede subir a mitad de obra?": "Can the price go up halfway through the job?",
    "No. El presupuesto que firmas incluye todas las partidas. Si surge algo imprevisto, te lo decimos antes de hacerlo, no en la factura final.": "No. The quote you sign covers every item. If something unexpected comes up, we tell you before doing it, not on the final invoice.",
    "¿Cuánto tarda una cocina?": "How long does a kitchen take?",
    "Entre 3 y 5 semanas, según el tamaño y si hay que mover instalaciones. Es un plazo orientativo: te damos la fecha exacta en el presupuesto.": "Between 3 and 5 weeks, depending on the size and whether pipes or wiring need moving. It's an approximate timeframe: we'll give you the exact date in the quote.",
    "¿Necesito algún permiso?": "Do I need a permit?",
    "Depende de si cambias la distribución o solo los acabados. Lo comprobamos en la visita y, si hace falta, nos encargamos del trámite.": "It depends on whether you're changing the layout or just the finishes. We check it during the visit and, if needed, we take care of the paperwork.",
    "¿Puedo seguir cocinando en casa durante la obra?": "Can I keep cooking at home during the work?",
    "Durante los días de instalación eléctrica y de fontanería, no. El resto de la obra no impide usar el resto de la casa.": "Not during the electrical and plumbing installation days. The rest of the work doesn't stop you using the rest of the house.",
    "¿Qué pasa si algo falla después de terminar?": "What happens if something goes wrong after it's finished?",
    "Queda cubierto por la garantía por escrito del contrato. Nos llamas y volvemos.": "It's covered by the written warranty in the contract. You call us and we come back.",
    "¿Empezamos por tu cocina?": "Shall we start with your kitchen?",
    "Pide presupuesto y te lo entregamos por escrito, partida por partida.": "Get a quote and we'll give it to you in writing, item by item.",
    "Cocinas · Cota Cero Reformas": "Kitchens · Cota Cero Reformas",
    "Cuéntanos tu reforma y te enviamos un presupuesto cerrado, sin compromiso.": "Tell us about your renovation and we'll send you a fixed-price quote, no obligation.",
    "/ Contacto": "/ Contact",
    "Pide tu presupuesto": "Get your quote",
    "Cuéntanos qué quieres reformar y te contactamos con un presupuesto cerrado.": "Tell us what you want to renovate and we'll get in touch with a fixed-price quote.",
    "Tipo de obra": "Type of work",
    "Reforma integral": "Full renovation",
    "Otra": "Other",
    "m² aproximados": "approximate m²",
    "(opcional)": "(optional)",
    "Nombre": "Name",
    "Teléfono": "Phone",
    "Mensaje": "Message",
    "He leído y acepto la": "I have read and accept the",
    "política de privacidad": "privacy policy",
    "Qué pasa después": "What happens next",
    "Revisamos tu solicitud y, si falta algún dato, te llamamos para completarlo.": "We review your request and, if anything is missing, we'll call you to complete it.",
    "Concretamos una visita para ver la vivienda, sin compromiso.": "We arrange a visit to see the property, no obligation.",
    "Te entregamos el presupuesto cerrado, por escrito, en los días siguientes a la visita.": "We give you the fixed-price quote, in writing, in the days after the visit.",
    "¿Prefieres hablarlo?": "Would you rather talk it through?",
    "Contacto · Cota Cero Reformas": "Contact · Cota Cero Reformas",
    "Reformamos cocinas, baños y viviendas completas con presupuesto cerrado y fecha de entrega en contrato. Pide presupuesto sin compromiso.": "We renovate kitchens, bathrooms and full homes with a fixed-price quote and a handover date in the contract. Get a quote, no obligation.",
    "Antes de tocar una pared, hacemos el plano": "Before we touch a wall, we draw the plan",
    "Precio cerrado, fecha firmada y un equipo que no cambia a mitad de obra.": "Fixed price, a signed date, and a team that doesn't change halfway through.",
    "Esquina de un plano de vivienda con sus medidas": "Corner of a home floor plan with its measurements",
    "Así se dibuja tu reforma": "This is how your renovation gets drawn up",
    "Elige la estancia y te contamos qué hacemos, cómo y en cuánto tiempo.": "Choose the room and we'll tell you what we do, how, and how long it takes.",
    "Plano de una vivienda: cocina, baño y el resto de la casa": "Floor plan of a home: kitchen, bathroom and the rest of the house",
    "Toda la casa": "The whole house",
    "Salón": "Living room",
    "Dormitorio": "Bedroom",
    "Cambiamos la cocina completa: muebles, electrodomésticos, instalación eléctrica y de agua, y acabados. Coordinamos los oficios para no tenerla parada más de lo necesario.": "We replace the whole kitchen: units, appliances, electrical and water installation, and finishes. We coordinate the trades so it's out of use for as little time as possible.",
    "Plazo orientativo: entre 3 y 5 semanas.": "Approximate timeframe: 3 to 5 weeks.",
    "Ver cocinas": "View kitchens",
    "Renovamos el baño desde cero: fontanería, alicatado, sanitarios y mampara. Revisamos primero las bajantes y la impermeabilización, no solo lo que se ve.": "We renovate the bathroom from scratch: plumbing, tiling, fittings and shower screen. We check the drainpipes and waterproofing first, not just what you can see.",
    "Plazo orientativo: entre 2 y 4 semanas.": "Approximate timeframe: 2 to 4 weeks.",
    "Ver baños": "View bathrooms",
    "Nos encargamos de la vivienda completa: distribución, instalaciones, carpintería y acabados, con un solo interlocutor.": "We take care of the whole home: layout, installations, carpentry and finishes, with a single point of contact.",
    "Plazo orientativo: entre 8 y 14 semanas, según los metros.": "Approximate timeframe: 8 to 14 weeks, depending on the size.",
    "Ver reformas integrales": "View full renovations",
    "Lo que firmamos contigo": "What we sign with you",
    "Las tres cosas que más preocupan antes de una reforma son el precio, el plazo y el desorden. Por eso van en el contrato.": "The three things people worry about most before a renovation are the price, the timeframe and the mess. That's why they're in the contract.",
    "Precio cerrado por escrito": "Fixed price in writing",
    "Lo que firmamos es lo que pagas, sin partidas que aparecen a mitad de obra.": "What we sign is what you pay, no extra items appearing halfway through the job.",
    "Fecha en el contrato": "Date in the contract",
    "La entrega tiene una fecha firmada, no una estimación de boca.": "The handover has a signed date, not a verbal estimate.",
    "Equipo propio": "Our own team",
    "Los oficios que entran en tu casa son nuestro equipo, no subcontratas de última hora.": "The trades who come into your home are our own team, not last-minute subcontractors.",
    "Obra limpia cada día": "A clean site every day",
    "Antes de irnos, recogemos: escombro fuera y suelos protegidos, todos los días.": "Before we leave, we tidy up: rubble out and floors protected, every day.",
    "Garantía por escrito": "Written warranty",
    "Lo que hacemos queda garantizado por contrato, no de palabra.": "What we do is guaranteed by contract, not just by word of mouth.",
    "De la visita a las llaves": "From the visit to the keys",
    "Visita": "Visit",
    "Vemos la vivienda y hablamos de lo que necesitas, sin compromiso.": "We see the property and talk about what you need, no obligation.",
    "Presupuesto cerrado": "Fixed-price quote",
    "Te lo entregamos por escrito, partida por partida.": "We give it to you in writing, item by item.",
    "Planificación": "Planning",
    "Fijamos fechas, materiales y quién hace qué, antes de tocar nada.": "We set dates, materials and who does what, before touching anything.",
    "Obra": "Work",
    "Empezamos en la fecha acordada y protegemos lo que no se reforma.": "We start on the agreed date and protect what isn't being renovated.",
    "Entrega de llaves": "Handover",
    "Revisamos juntos cada detalle antes de darte la vivienda por terminada.": "We check every detail together before handing the property over as finished.",
    "Antes y después": "Before and after",
    "Arrastra la línea para comparar.": "Drag the line to compare.",
    "Foto: piso antes de la reforma, distribución original, 4:3": "Photo: flat before the renovation, original layout, 4:3",
    "Foto: piso terminado, salón abierto, 4:3": "Photo: finished flat, open-plan living room, 4:3",
    "Comparar antes y después del piso de los años 70": "Compare before and after of the 1970s flat",
    "Piso de los años 70": "1970s flat",
    "Redistribuimos un piso con pasillos estrechos y habitaciones cerradas: ahora tiene un salón más grande y un baño más.": "We redesigned the layout of a flat with narrow corridors and closed-off rooms: it now has a bigger living room and an extra bathroom.",
    "Lo que cuentan después": "What they say afterwards",
    "Nos dieron el presupuesto cerrado antes de empezar y no cambió ni un euro en toda la obra. Recogían el escombro cada tarde, así que seguíamos viviendo cerca sin que fuera un caos. La entrega fue el día que decía el contrato.": "They gave us the fixed-price quote before starting and it didn't change by a single euro through the whole job. They cleared the rubble every afternoon, so we could keep living nearby without it turning into chaos. The handover was on the day the contract said.",
    "Pide tu presupuesto, sin compromiso": "Get your quote, no obligation",
    "Te lo entregamos por escrito, con precio cerrado y fecha de entrega.": "We give it to you in writing, with a fixed price and handover date.",
    "Cota Cero Reformas · Reformas integrales, cocinas y baños": "Cota Cero Reformas · Full renovations, kitchens and bathrooms",
    "Esta web no usa cookies propias ni de analítica. Qué recursos externos carga y qué información pueden recibir.": "This website doesn't use its own or analytics cookies. What external resources it loads and what information they may receive.",
    "/ Cookies": "/ Cookies",
    "Política de cookies": "Cookie policy",
    "1. Esta web no usa cookies propias": "1. This website doesn't use its own cookies",
    "Cota Cero Reformas no instala cookies propias ni de analítica en tu navegador. No hay medición de tráfico, ni perfiles de navegación, ni publicidad basada en tu actividad en esta web.": "Cota Cero Reformas doesn't install its own or analytics cookies on your browser. There's no traffic tracking, no browsing profiles, and no advertising based on your activity on this website.",
    "2. Sin recursos de terceros al navegar": "2. No third-party resources while browsing",
    "Las tipografías y la librería que anima el plano están alojadas en esta misma web. Mientras navegas, tu navegador no hace peticiones a servidores de otras empresas.": "The fonts and the library that animates the floor plan are hosted on this website. While you browse, your browser makes no requests to other companies' servers.",
    "3. Formulario de contacto": "3. Contact form",
    "Si rellenas y envías el formulario de la página «Pedir presupuesto», los datos que escribes se envían a Formspree, Inc., el proveedor que gestiona la recepción de esos formularios. Este envío ocurre solo si tú decides enviar el formulario; se detalla en la": "If you fill in and submit the form on the «Get a quote» page, the details you enter are sent to Formspree, Inc., the provider that handles receiving these forms. This only happens if you choose to submit the form; it's detailed in the",
    "4. Cambios en esta política": "4. Changes to this policy",
    "Si en algún momento añadimos analítica o cualquier servicio que use cookies, lo indicaremos aquí y te pediremos permiso antes de activarlo.": "If we ever add analytics or any service that uses cookies, we will say so here and ask for your permission before turning it on.",
    "Política de cookies · Cota Cero Reformas": "Cookie policy · Cota Cero Reformas",
    "Qué datos recogemos al pedir presupuesto, con qué finalidad y cómo ejercer tus derechos de protección de datos.": "What data we collect when you request a quote, for what purpose, and how to exercise your data protection rights.",
    "/ Privacidad": "/ Privacy",
    "Política de privacidad": "Privacy policy",
    "1. Responsable del tratamiento": "1. Data controller",
    "2. Datos que recogemos y finalidad": "2. Data we collect and purpose",
    "A través del formulario de la página «Pedir presupuesto» recogemos los siguientes datos: tipo de obra, metros cuadrados aproximados (opcional), nombre, teléfono, correo electrónico (opcional) y el mensaje que quieras añadir. Los usamos únicamente para responder a tu solicitud de presupuesto: contactarte, concretar una visita y, en su caso, entregarte el presupuesto por escrito.": "Through the form on the «Get a quote» page we collect the following data: type of work, approximate square metres (optional), name, phone number, email (optional) and any message you want to add. We use it only to respond to your quote request: to contact you, arrange a visit and, where applicable, give you the quote in writing.",
    "3. Base legal": "3. Legal basis",
    "El tratamiento se basa en tu consentimiento, que prestas al marcar la casilla de privacidad y enviar el formulario, y en la aplicación de medidas precontractuales a petición tuya (artículo 6.1.b del RGPD), ya que nos escribes para pedir un presupuesto.": "The processing is based on your consent, given when you tick the privacy checkbox and submit the form, and on the application of pre-contractual measures at your request (article 6.1.b of the GDPR), since you're writing to us to ask for a quote.",
    "4. Encargado del tratamiento": "4. Data processor",
    "El formulario de contacto se gestiona a través de Formspree, Inc., con sede en Estados Unidos, que actúa como encargado del tratamiento y recibe los datos que envías para hacérnoslos llegar. Formspree aplica sus propias garantías de seguridad; puedes consultar su política de privacidad en su web.": "The contact form is managed through Formspree, Inc., based in the United States, which acts as the data processor and receives the data you send so it can reach us. Formspree applies its own security safeguards; you can check its privacy policy on its website.",
    "5. Conservación de los datos": "5. Data retention",
    "Conservamos los datos mientras dure la relación con la solicitud de presupuesto y, tras finalizar, durante los plazos legales aplicables para atender posibles responsabilidades. Pasado ese tiempo, se eliminan o se anonimizan.": "We keep the data for as long as the quote request relationship lasts and, once it ends, for the legal periods that apply to cover any possible liabilities. After that time, it is deleted or anonymised.",
    "6. Tus derechos": "6. Your rights",
    "Puedes ejercer tus derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad escribiendo a [EMAIL DE CONTACTO], indicando el derecho que quieres ejercer y adjuntando un documento que acredite tu identidad.": "You can exercise your rights of access, rectification, erasure, objection, restriction of processing and portability by writing to [EMAIL DE CONTACTO], stating which right you want to exercise and attaching a document proving your identity.",
    "7. Reclamación ante la autoridad de control": "7. Complaints to the supervisory authority",
    "Si consideras que el tratamiento de tus datos no se ajusta a la normativa, puedes presentar una reclamación ante la Agencia Española de Protección de Datos (AEPD),": "If you believe your data hasn't been processed in line with the law, you can file a complaint with the Agencia Española de Protección de Datos (AEPD),",
    "Política de privacidad · Cota Cero Reformas": "Privacy policy · Cota Cero Reformas",
    "Reforma integral de la vivienda: distribución, instalaciones, carpintería y acabados, con un solo interlocutor y presupuesto cerrado.": "Full renovation of your home: layout, systems, carpentry and finishes, with a single point of contact and a fixed-price quote.",
    "/ Reformas integrales": "/ Full renovations",
    "Toda la casa, con un solo interlocutor": "The whole house, one point of contact",
    "Foto: salón reformado, luz natural, 16:9": "Photo: renovated living room, natural light, 16:9",
    "Redistribución de espacios, si hace falta": "Reworking the layout, if needed",
    "Instalación eléctrica y de fontanería completas": "Full electrical and plumbing installation",
    "Carpintería interior y exterior": "Interior and exterior carpentry",
    "Suelos y alicatados de toda la vivienda": "Flooring and tiling throughout the home",
    "Pintura y acabados": "Paint and finishes",
    "Cocina y baños incluidos en el proyecto": "Kitchen and bathrooms included in the project",
    "Gestión de permisos y trámites con la comunidad": "Permits and paperwork with the residents' association",
    "Empezamos por el plano": "We start with the floor plan",
    "Empezamos por el plano: cómo quieres distribuir la vivienda y por qué.": "We start with the floor plan: how you want the home laid out, and why.",
    "Planificamos el orden": "We plan the order of work",
    "Planificamos el orden de los oficios antes de pedir el primer material.": "We plan the order of trades before ordering the first materials.",
    "Un jefe de obra": "A site manager",
    "Un jefe de obra es tu único contacto durante toda la reforma.": "A site manager is your only point of contact throughout the renovation.",
    "Revisamos el avance": "We check progress",
    "Revisamos el avance cada semana contigo, no solo al final.": "We review progress with you every week, not just at the end.",
    "¿El precio cerrado incluye cocina y baños?": "Does the fixed price include the kitchen and bathrooms?",
    "Si están dentro del proyecto que presupuestamos, sí. Todo lo acordado va en el mismo precio, sin partidas sueltas después.": "If they're part of the project we quote for, yes. Everything agreed is included in the same price, with no extra items later.",
    "¿Cuánto dura una reforma integral?": "How long does a full renovation take?",
    "Entre 8 y 14 semanas, según los metros y si cambia la distribución. Es un plazo orientativo: te damos la fecha real en el presupuesto.": "Between 8 and 14 weeks, depending on the size and whether the layout changes. It's an approximate timeframe: we give you the real date in the quote.",
    "¿Quién se encarga de los permisos?": "Who deals with the permits?",
    "Nosotros. Comprobamos qué necesita tu comunidad o el ayuntamiento y hacemos el trámite antes de empezar.": "We do. We check what your residents' association or the council requires and handle the paperwork before starting.",
    "¿Dónde va el escombro?": "Where does the rubble go?",
    "Lo retiramos con contenedor autorizado y lo recogemos cada día de obra, no se acumula en la vivienda.": "We remove it with an authorised skip and collect it every day of work, so it doesn't pile up in the home.",
    "¿Qué garantía tiene la reforma completa?": "What warranty does the full renovation have?",
    "La misma en toda la obra: por escrito, en el contrato, sin depender de a quién le preguntes.": "The same across the whole job: in writing, in the contract, not depending on who you ask.",
    "¿Empezamos por el plano de tu casa?": "Shall we start with the floor plan of your home?",
    "Visita, presupuesto cerrado y fecha de entrega firmada.": "Site visit, fixed-price quote and a signed handover date.",
    "Reformas integrales · Cota Cero Reformas": "Full renovations · Cota Cero Reformas",
    "después": "after",
    "Escribe tu nombre.": "Enter your name.",
    "Escribe un teléfono de al menos 9 cifras.": "Enter a phone number with at least 9 digits.",
    "Necesitamos que aceptes la política de privacidad.": "Please accept the privacy policy.",
    "Enviando…": "Sending…",
    "Recibido. Te llamamos en un día laborable para concretar la visita.": "Received. We'll call you within one working day to arrange the visit.",
    "No se ha podido enviar. Llámanos al 600 000 000 y lo vemos por teléfono.": "It couldn't be sent. Call us on 600 000 000 and we'll sort it out by phone.",
    "2. Recursos externos que se cargan": "2. External resources that are loaded",
    "Aun sin usar cookies, la página carga algunos recursos alojados en servidores de terceros para funcionar correctamente. Al cargarlos, esos terceros pueden recibir tu dirección IP y datos técnicos propios de cualquier petición a un servidor web:": "Even without using cookies, the page loads some resources hosted on third-party servers to work properly. When loaded, those third parties may receive your IP address and the technical data that comes with any request to a web server:",
    ": las tipografías del sitio (Bricolage Grotesque y Source Serif 4) se cargan desde los servidores de Google Fonts.": ": the site's typefaces (Bricolage Grotesque and Source Serif 4) are loaded from Google Fonts' servers.",
    "GSAP (vía cdnjs, Cloudflare)": "GSAP (via cdnjs, Cloudflare)",
    ": la librería que anima el dibujo del plano en la portada se carga desde la red de Cloudflare (cdnjs).": ": the library that animates the drawing of the plan on the homepage is loaded from Cloudflare's network (cdnjs).",
    "4. Cómo desactivar estos recursos": "4. How to disable these resources",
    "Puedes bloquear estas peticiones a terceros desde la configuración de tu navegador o con una extensión de bloqueo; la web seguirá funcionando, aunque puede que el texto o la animación del plano se vean con el estilo por defecto del navegador.": "You can block these third-party requests from your browser settings or with a blocking extension; the website will keep working, though the text or the plan animation may appear in the browser's default style."
  }
};
/* ── TRAD:fi ── */

/* Amb el diccionari carregat, el motor ja pot fer la feina. */
if (window.I18N) window.I18N.inicia();
